import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import StoreInfo from 'components/StoreInfo';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Salmon Cookies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <h1 className={inter.className}>Salmon Cookies</h1>
        </div>

        <StoreInfo />

        <div className={styles.grid}>
          <Link
            href="/sales_data"
            className={styles.card}
          >
            <h2 className={inter.className}>
              Sales Data <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              See our sales data per location.
            </p>
          </Link>
        </div>
      </main>
    </>
  )
}
